@startyaml
!theme plain
1. LOC-Quản lý vị trí:
    - Quản lý địa chỉ (100%)
    - Quản lý địa bàn
    - Quản lý vị trí
2. PRM-Quản lý cấu hình Policy Rule:
    - Quản lý PolicyRule
    - Quản lý PolicyAction
    - Quản lý PolicyCondition
    - Quản lý PolicyVariable
3. ECM-Quản lý danh mục dùng chung:
4. CORE:
    4.1.Quản lý cấu hình Form động:
        - Search Filter (100%)
        - Modal Form (100%)
        - Properties Form (100%)
        - Product Design
    4.2.Quản lý thuộc tính:
        - Quản lý cấu hình Characteristic (100%)
        - Quản lý PickList (100%)
        - Quản lý ObjectType (100%)
    4.3. Quản lý Simulator:
        - API Giả lập dữ liệu trả về theo kịch bản (100%)
        - Giả lập dữ liệu trả về thông qua event ( Kafka) (100%)
        - Giả lập api hỗ trợ giao thức Http soap(XML) (100%)
    4.4. Quản lý TMF OpenAPI:
        - API Validation (100%)
        - API Author(100%)
        - API Event(100%)
        - API Invoker(100%)
    4.5. Tích hợp Service Activation:
        - Tích hợp BNM
        - Tích hợp SPI
    4.6. Capture Data Change(CDC):
        - Xây dựng data Model(1%)
        - Xây dựng CDC (100%)
        - Xây dựng CDC Event (100%)
    4.7. Quy trình động (n8n workflow automation):
        - Kết nối ứng dụng (App Integration) (100%)
        - Tự động hóa quy trình (Workflow Automation)
        - Kích hoạt và lập lịch (Triggers & Scheduling)
    4.8. MicroFrontend:
5. Devops:
    - Triển khai servie lên hệ thống k8s (100%)
    - Triển khai api gateway ( krakenD)
@endyaml